modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Exploding-Creeper/SimpleSplashScreen/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-splash-screen" #optional
logoFile="logo_light.png" #optional
credits="Thanks to Motschen who made the original Fabric version of this mod" #optional
authors="${mod_author}"
description = '''
A mod that allows you to customize the Minecraft Loading Screen to your liking
'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type="required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"